main:
	g++ Account.h Account.cpp AccountArray.h AccountArray.cpp BankingCommonDecl.h BankingSystemMain.cpp AccountHandler.h AccountHandler.cpp NormalAccount.h HighCreditAccount.h String.h String.cpp

clean:
	rm a.out
